### ISSUE TITLE
Add test for direct and pooled stacking

### ISSUE THREAD

**Issue by friedger** [hirosystems/stacks-2-1-testing#18]
1. Alice stacks 50m with a pool
2. Bob stacks 50m directly
3. Bob delegates 50m to pool
4. Cloe locks Alice 50m
5. Cloe calls delegate-stack-increase for Bob

**Comment by jcnelson** [comment]
Can you explain how someone can call `delegate-stack-stx` on behalf of Bob when Bob has already stacked via `stack-stx`?

**Comment by friedger** [comment]
@jcnelson Sorry for the incompleteness. I had in mind that the issue is about exploring different scenarios.
The expected outcome would be that the `delegate-stack-tx` fails
Out of my head, I don't know whether `delegate-stack-increase` would fail.

**Comment by friedger** [comment]
I have updated the issue description to cover 1 specific flow

**Comment by friedger** [comment]
Addressed in #31

**Comment by friedger** [comment]
There is now a test added that also shows the error when using `delegate-stack-extend`

**Comment by jo-tm** [comment]
Closed by https://github.com/hirosystems/stacks-2-1-testing/pull/31
