### ISSUE TITLE
Add test for several stack-stx, stack-increase in one block

### ISSUE THREAD

**Issue by friedger** [hirosystems/stacks-2-1-testing#30]
Add test with several stack-stx and stack-increase calls to show
that "we cannot determine the order in which stack-increase were called within the same block.  Because stack-increase alters reward-cycle-total-stacked, it means that we don't know the value of total-ustx that was erroneously written to each PoX address's entry affected by this block. This, in turn, prevents us from subtracting out this value in order to recover the solo stacker's original value"

**Comment by friedger** [comment]
In the original comment it was talked about stack-extend, I have adapted it to talk about stack-increase instead.

**Comment by friedger** [comment]
Not sure what to exactly assert here. If you have more input please let me know.

**Comment by obycode** [comment]
How about a test where Alice and Bob stack the same amount, then increase by the same amount, but then show that their `total-ustx` values in the map are different.

**Comment by jo-tm** [comment]
WIP here https://github.com/hirosystems/stacks-2-1-testing/issues/30
