### ISSUE TITLE
Is deno/clarinet used at all when a test runs?

### ISSUE THREAD

**Issue by moodmosaic** [hirosystems/stacks-2-1-testing#61]
What is the high-level architecture of this project? Is deno/clarinet involved (if so, where)? Just trying to understand how it all works, as part of the work in progress at https://github.com/stacks-network/stacks-blockchain/issues/3845.

**Comment by kantai** [comment]
Clarinet is only invoked in this project via `stacks-devnet-js` -- that is a component of clarinet built here (https://github.com/hirosystems/clarinet/tree/develop/components/stacks-devnet-js). That library coordinates end-to-end tests like those defined in this repository by (1) instantiating a docker container running a bitcoin regtest node, and (2) instantiating a docker container running a stacks-node pointed at that bitcoin docker container. Therefore these tests are running against full Stacks nodes and not the clarinet/deno runtime.

**Comment by friedger** [comment]
Feel free to re-open if you have more questions.
